### ISSUE TITLE
Apply PyBind to wrap libsnark into a Python module

### ISSUE THREAD

**Issue by Benardi** [OpenMined/PyZPK#39]
**Is your feature request related to a problem? Please describe.**
I would like to have the libsnark C++ lib provided as a Python module 

**Describe the solution you'd like**
A combination of the submodules PyBind and libsnark into a Python module

**Comment by gargarchit** [comment]
Hi @Benardi, this is one of the main objectives during the GSoC period. Do we have to make a sample now or start working on this

**Comment by gargarchit** [comment]
I would like to work on this

**Comment by codeboy5** [comment]
I would also like to contribute to this issue.

**Comment by Benardi** [comment]
> Hi @Benardi, this is one of the main objectives during the GSoC period. Do we have to make a sample now or start working on this

This may or may not align with the objectives of the various candidates. 
The PyZPK project is intended as a contribution per se, so the work done here should be for real.

There will be much more work to be done before libsnark can be truly available everywhere as a Python module.

**Comment by Benardi** [comment]
I'll be adding both of you @gargarchit  @codeboy5  as contributors so you guys can synchronize and work on the same branch. Nonetheless, @gargarchit  will be the main assigne.

**Comment by codeboy5** [comment]
@gargarchit can you share your slack username?

**Comment by gargarchit** [comment]
Hi @codeboy5 My Slack Username: @Archit

**Comment by Benardi** [comment]
Updates ?

**Comment by gargarchit** [comment]
Hi, @Benardi
we have added initial imports and test file in the dev branch
Currently working to include libsnark for wrapping. We are trying out some of the methods which will make it easy. Also, we are trying the method used in PyDP.

**Comment by Benardi** [comment]
If you guys need me for something hit me up in Slack or over here.
